name: CI/CD Pipeline Deploy to Google Compute Engine

run-name: ${{ github.actor }} | Continuous Deployment by GitHub Actions 🚀

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to repo
      uses: 'actions/checkout@v3'

    - name: Google Auth
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCE_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.4.1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}
        export_default_credentials: true

    - name: Run command on prod server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        HOST: ${{ secrets.GCP_HOST }}
        USER: ${{ secrets.GCP_USER }}
      run: |
        command: 'echo Hello world'